### ISSUE TITLE
[Feature Request] Add option to clone a folder

### ISSUE THREAD

**Issue by DevashishPatwal** [anadius/gd-efc#6] opened 2020-08-04 04:46 UTC
Right now if I want to copy a folder I load the link and manually create a folder in my drive and copy files to that folder. It would be cool if folder is created automatically and all files are copied to it.

**Comment by anadius** [comment] 2020-08-04 07:01
Duplicate of #1.

**Closed by anadius** 2020-08-04 07:01 UTC
